import os

RABBITMQ_HOST = os.getenv('RABBITMQ_HOST')
RABBITMQ_PORT = os.getenv('RABBITMQ_PORT')
RABBITMQ_DEFAULT_USER = os.getenv('RABBITMQ_DEFAULT_USER')
RABBITMQ_DEFAULT_PASS = os.getenv('RABBITMQ_DEFAULT_PASS')
VHOST_NAME = os.getenv('VHOST_NAME')
RABBITMQ_TEST_QUEUE = os.getenv('RABBITMQ_TEST_QUEUE')
RABBITMQ_DATA_QUEUE = os.getenv('RABBITMQ_DATA_QUEUE')
RABBITMQ_TRAIN_QUEUE = os.getenv('RABBITMQ_TRAIN_QUEUE')


SAVE_VIDEO_PATH = "/media/train_videos/"